# Web Scraping Assignment 4

In [1]:
#importing necessary libraries
import selenium
import pandas as pd
import time
# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
#Importing requests
import requests

# importing regex
import re

### Q1- Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details: A) Rank
B) Name
C) Artist
D) Upload date E) Views

In [3]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver 2")
#open a website
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_2388/2011959556.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver 2")

In [4]:
#Creating empty list
Rank = []
Name = []
Artist = []
Upload_date = []
Views = []

#Scraping data of rank details
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[1]")[:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_2388/2424928880.py:10: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[1]")[:30]:

In [5]:
#Scraping data of video names
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[2]")[:30]:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_2388/1119555843.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[2]")[:30]:

In [6]:
#Scraping data of artist name
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[3]")[:30]:
        Artist.append(i.text)
except NoSuchElementException:        
    Artist.append('-')

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_2388/1679847225.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[3]")[:30]:

In [7]:
#Scraping data of upload date
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[5]")[:30]:
        Upload_date.append(i.text)
except NoSuchElementException:        
    Upload_date.append('-')

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_2388/4163564491.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[5]")[:30]:

In [8]:
#Scraping data of views
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[4]")[:30]:
        Views.append(i.text)
except NoSuchElementException:
    Views.append('-')

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_2388/3743936498.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']//tbody//tr//td[4]")[:30]:

In [9]:
#DATA FRAMEING
Youtube=pd.DataFrame({})
Youtube['Rank'] = Rank
Youtube['Name'] = Name
Youtube['Artist'] = Artist
Youtube['Uploaded Date'] = Upload_date
Youtube['Views'] = Views

In [10]:
#Printing data frame
Youtube

,Rank,Name,Artist,Uploaded Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.72
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.85
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.36
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.72
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.52
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.40
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.64
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.58
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.57
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.49
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.43
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.08
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.94
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.69
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.58
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.58
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.54
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.45
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.36
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.29
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.28
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.27
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.24
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.23
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.21
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.21
26,27.,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.17
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.17
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.14
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.08

In [33]:
driver.close()

### Q2- Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [37]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.bcci.tv/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/1623365536.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [77]:
#Creating empty list
Match_title = []
Series = []
Place = []
Date = []
Time = []

In [39]:
Int_button=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
Int_button.click()

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4273572358.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  Int_button=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')

In [80]:
titles_tags=driver.find_elements_by_xpath("//span[@class='ng-binding']")
titles_tags[0:1]

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/3886242235.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  titles_tags=driver.find_elements_by_xpath("//span[@class='ng-binding']")

In [81]:
for i in titles_tags:
    title=i.text
    Match_title.append(title)
Match_title

['SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022']

In [82]:
place_tags=driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
for i in place_tags:
    Place.append(i.text[10: ])
Place

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/1478588955.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  place_tags=driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")

[' Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 ' Saurashtra Cricket Association Stadium, Rajkot',
 ' M Chinnaswamy Stadium, Bengaluru']

In [83]:
series = driver.find_elements_by_xpath("//div[@class='fixture-card-mid d-flex align-items-center justify-content-between']")
for i in series:       
    if i.text is None :
        Series.append("--") 
    else:
        Series.append(i.text.replace("\n"," "))

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/2068717203.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  series = driver.find_elements_by_xpath("//div[@class='fixture-card-mid d-flex align-items-center justify-content-between']")

In [84]:
Series

['India vs South Africa', 'India vs South Africa', 'India vs South Africa']

In [85]:
for i in driver.find_elements_by_xpath("//div[@class='match-top-info d-flex align-items-center justify-content-between']"):
    Date.append(i.text[0:11])       
Date

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/3121480614.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@class='match-top-info d-flex align-items-center justify-content-between']"):

['14 JUN 2022', '17 JUN 2022', '19 JUN 2022']

In [86]:
for i in driver.find_elements_by_xpath("//div[@class='match-top-info d-flex align-items-center justify-content-between']"):
    Time.append(i.text[12: ])       
Time

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/870035167.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@class='match-top-info d-flex align-items-center justify-content-between']"):

['5:30 PM +04', '5:30 PM +04', '5:30 PM +04']

In [87]:
#data framing

BCCI=pd.DataFrame({})
BCCI['Match Title'] = Match_title
BCCI['Series'] = Series
BCCI['Place'] = Place
BCCI['Date'] = Date
BCCI['Time'] = Time
BCCI

,Match Title,Series,Place,Date,Time
0,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India vs South Africa,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stad...,14 JUN 2022,5:30 PM +04
1,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India vs South Africa,"Saurashtra Cricket Association Stadium, Rajkot",17 JUN 2022,5:30 PM +04
2,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India vs South Africa,"M Chinnaswamy Stadium, Bengaluru",19 JUN 2022,5:30 PM +04

In [95]:
driver.close()

### Q3- Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [89]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.guru99.com/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4032472600.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [91]:
#Going to search bar and searching for selenium exception

ser_bar = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
ser_bar.send_keys("selenium exception handling")
ser_but = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button").click()
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/2989475008.py:3: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  ser_bar = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/2989475008.py:5: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  ser_but = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button").click()

In [92]:
urls = driver.find_element_by_xpath("//div[@class='gsc-expansionArea']//div//a")
page_url = urls.get_attribute("href")

driver.get(page_url)
time.sleep(5)

#Scraping data of names of exceptions
Name = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[1]")[1:]:
    Name.append(i.text)
    
#Scraping data of descriptions of exceptions  
Description = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[2]")[1:]:
    Description.append(i.text)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4243381935.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  urls = driver.find_element_by_xpath("//div[@class='gsc-expansionArea']//div//a")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4243381935.py:9: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[1]")[1:]:
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4243381935.py:14: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[2]")[1:]:

In [94]:
#data framing

Guru=pd.DataFrame({})
Guru['Name of Exception'] = Name
Guru['Description of Exception'] = Description
Guru

,Name of Exception,Description of Exception
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [109]:
driver.close()

## Q4-Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [110]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.statisticstimes.com/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/848147346.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [111]:
urls = driver.find_element_by_xpath("//div[@class='dropdown-content']//a[3]")
page = urls.get_attribute("href")
#Going to indian economy page
driver.get(page)  
time.sleep(5)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/3872698748.py:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  urls = driver.find_element_by_xpath("//div[@class='dropdown-content']//a[3]")

In [112]:
#get the url of page containing GDP of indian states
state_GDP = driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a")
GDP = state_GDP.get_attribute("href")

driver.get(GDP)
time.sleep(6)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4231724697.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  state_GDP = driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a")

In [115]:
Rank=[]
State=[]
GSDP_19_20=[]
GSDP_18_19=[]
Share_18_19=[]
GDP_billion=[]

In [117]:
#Scraping data of rank
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[1]"):
    Rank.append(i.text)

#Scraping state name
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[2]"):
    State.append(i.text)

    
# Scraping GSDP at current price (19-20)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[3]"):
    GSDP_19_20.append(i.text)

    
#Scraping GSDP at current price (18-19)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[4]"):
    GSDP_18_19.append(i.text)

    
#Scraping Share(18-19)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[5]"):
    Share_18_19.append(i.text)

    
#Scraping GDP($ billion)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[6]"):
    GDP_billion.append(i.text)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4110513708.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[1]"):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4110513708.py:6: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[2]"):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4110513708.py:11: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[3]"):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4110513708.py:16: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[4]"):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4110513708.py:21: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[5]"):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/4110513708.py:26: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[6]"):

In [120]:
#DATA FRAMEING
Statistics=pd.DataFrame({})
Statistics['Rank'] = Rank
Statistics['State'] = State
Statistics['GSDP(19-20)'] = GSDP_19_20
Statistics['GSDP(18-19)'] = GSDP_18_19
Statistics['Share(18-19)'] = Share_18_19
Statistics['GDP($ billion)'] = GDP_billion

Statistics

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [142]:
driver.close()

### Q5-Scrape the details of trending repositories on Github.com. Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [143]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://github.com/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/1480056307.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [144]:
#Getting explore button and clicking on it
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()

#Selecting trending option
trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/3472573901.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/3472573901.py:5: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")

In [145]:
#Creating empty list for scraping into it

repository = []
url = []
Description = []
Contributors = []
Language = []
lang = []

In [149]:
#Fetching urls for each repository
repos = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repos:
    url.append(i.get_attribute("href"))

    
#Scraping data of repository title
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository.append(i.text)

    
#Scraping data from every repository page
for i in url:
    driver.get(i)
    time.sleep(3)
    
    
    #Scraping data of decription
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 my-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    #Scraping data of contributors
    try:
        cont_tags = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(cont_tags.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
     #fetching Languages used
    try:
        for i in driver.find_elements_by_xpath("//span[@class='color-text-primary text-bold mr-1']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/292172632.py:2: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  repos = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/292172632.py:8: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/292172632.py:21: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  desc = driver.find_element_by_xpath("//p[@class='f4 my-3']")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/292172632.py:29: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cont_tags = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/292172632.py:37: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//span[@class='color-text-primary text-bold mr-1']"):

In [150]:
print(len(repository),len(Description),len(Language),len(Contributors))

25 25 25 25

In [151]:
#Data framing

Github=pd.DataFrame({})
Github['Repository title'] = repository
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language

Github

,Repository title,Repository description,Contributors count,Language used
0,digitalocean / nginxconfig.io,⚙️ NGINX config generator on steroids 💉,41,[]
1,home-assistant / core,🏡 Open source home automation that puts local ...,"2,894",[]
2,borisdayma / dalle-mini,DALL·E Mini - Generate images from a text prompt,18,[]
3,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,455",[]
4,TheAlgorithms / Python,All Algorithms implemented in Python,812,[]
5,sheepla / pingu,🐧ping command but with pingu,5,[]
6,adrianhajdin / project_fitness_app,-,-,[]
7,iptv-org / iptv,Collection of publicly available IPTV channels...,172,[]
8,ossu / computer-science,🎓 Path to a free self-taught education in Comp...,122,[]
9,TBD54566975 / collaboration,"""Collaboration"" - a word we made up which comb...",3,[]
10,medusajs / medusa,The open-source Shopify alternative ⚡️,80,[]
11,skyline-emu / skyline,Run Nintendo Switch homebrew & games on your A...,16,[]
12,saharmor / dalle-playground,A playground to generate images from any text ...,3,[]
13,knadh / dns.toys,A DNS server that offers useful utilities and ...,7,[]
14,vaxerski / Hyprland,Hyprland is a dynamic tiling Wayland composito...,17,[]
15,microsoft / Data-Science-For-Beginners,"10 Weeks, 20 Lessons, Data Science for All!",89,[]
16,EbookFoundation / free-programming-books,📚 Freely available programming books,"1,960",[]
17,atom / atom,The hackable text editor,489,[]
18,awesome-selfhosted / awesome-selfhosted,A list of Free Software network services and w...,"1,060",[]
19,sherlock-project / sherlock,🔎 Hunt down social media accounts by username ...,157,[]
20,siyuan-note / siyuan,📕 SiYuan is a local-first personal knowledge m...,4,[]
21,CleverRaven / Cataclysm-DDA,Cataclysm - Dark Days Ahead. A turn-based surv...,"1,638",[]
22,Koenkk / zigbee2mqtt,"Zigbee 🐝 to MQTT bridge 🌉, get rid of your pro...",348,[]
23,freqtrade / freqtrade,"Free, open source crypto trading bot",223,[]
24,coolsnowwolf / lede,Lean's OpenWrt source,293,[]

In [185]:
driver.close()

### Q6-Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [187]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.billboard.com/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/2487809580.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [188]:
#Clicking on charts

charts=driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a").click()

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/1568030346.py:3: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  charts=driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a").click()

In [211]:
# clicking the hot 100
hot100=driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a")
hot100.click()

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/1137608878.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  hot100=driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a")

In [214]:
#creating empty list for scraping data
Song_name=[]
Artist_name=[]
Last_week_rank=[]
Peak_rank=[]
Weeks_on_board=[]

# scraping Song name
song = driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']")
for i in song:       
    Song_name.append(i.text.split('\n')[0])
    Artist_name.append(i.text.split('\n')[1])

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_812/2620525276.py:9: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  song = driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']")

In [232]:
for i in song:
    Last_week_rank.append(i.text.split('\n')[2])
    Peak_rank.append(i.text.split('\n')[3])
    Weeks_on_board.append(i.text.split('\n')[4])

In [234]:
print(len(Last_week_rank),len(Peak_rank),len(Weeks_on_board))

100 100 100

In [235]:
Billboard = pd.DataFrame({'Song Name': Song_name,
                         'Artist Name': Artist_name,
                         'Last week rank': Last_week_rank,
                         'Peak rank': Peak_rank,
                         'Weeks on board': Weeks_on_board})
Billboard

,Song Name,Artist Name,Last week rank,Peak rank,Weeks on board
0,As It Was,Harry Styles,1,1,9
1,First Class,Jack Harlow,2,1,8
2,Wait For U,Future Featuring Drake & Tems,3,1,5
3,About Damn Time,Lizzo,5,4,7
4,Heat Waves,Glass Animals,6,1,72
...,...,...,...,...,...
95,Love You Better,Future,84,12,5
96,Wild Hearts,Keith Urban,-,97,1
97,Last Night Lonely,Jon Pardi,-,98,1
98,7500 OBO,Tim McGraw,-,99,1
99,Until I Found You,Stephen Sanchez,-,100,1

In [7]:
driver.close()

### Q7-Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [8]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.naukri.com/hr-recruiters-consultants'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/1605854524.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

### the updated naukri.com website does not have recruiters tab on the home page. so directly used recruiters website.

In [10]:
#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3272183867.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  search=driver.find_element_by_xpath("//input[@class='sugInp']")

In [11]:
#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3512291310.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")

In [22]:
#scrapping names

Name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:           
    Name.append('No details')

time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2876290290.py:5: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")

In [23]:
#scrapping designation
Designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        Designation.append(i.text)
except NoSuchElementException:        
    Designation.append('No details')
    
time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2488204211.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")

In [24]:
#scrapping company names
Company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        Company.append(i.text)
except NoSuchElementException:
    Company.append('No details')

time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/4171030941.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")

In [25]:
#scrapping location names
Location=[]
try:
    loc=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[2]")
    for i in loc:   
        Location.append(i.text)
except NoSuchElementException:
    Location.append("No details")       
time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/770124772.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  loc=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[2]")

In [26]:
Skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        Skill.append(i.text)
except NoSuchElementException:
    Skill.append('No details')   
time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/943637952.py:3: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")

In [27]:
#creating dataframe
DS_Recruiters=pd.DataFrame({'Name':Name,
                'Designation':Designation,
                'Company':Company,
                "Location":Location,
                'Hire_for_Skillset':Skill})
DS_Recruiters

,Name,Designation,Company,Location,Hire_for_Skillset
0,Santhosh Kumar,Associate Manager Human Resources,Maveric Systems,Chennai,"It Recruitment, Campus Recruitment, Campus Hir..."
1,Gauri Bhosle,Human Resources,TCRC,Mumbai,"Operation Executive, Jr. Chemist/ Chemist, Aud..."
2,Surendra R,Company Recruiter,DSR Design & Engineering Solutions,Hyderabad / Secunderabad,"Design Engineering, AutoCAD, Solid Works"
3,Neha Pandey,Company Recruiter,Ingenious E-Brain Solutions Private Limited,Gurgaon,"B.tech, Operations, Business Development, Busi..."
4,Vinita Raut,Company Recruiter,Xpansion HR Solutions Private Limited,Pune,"Bde, Accounting, Education Counseling, Sales, ..."
5,BALA Sakthivelmuthu,Company Recruiter,E Vel,Madurai,"Html, Css, Javascript, Ui Development, Java, A..."
6,Anandi Bandekar,Deputy Manager Recruitment,GeBBS Healthcare Solutions,Mumbai,"CTO, VP, Sr.Manager"
7,Cameo,Company Recruiter,Cameo Corporate Services,Chennai,"Latex, Paginator, Tex"
8,Cameo,Company Recruiter,Cameo Corporate Services,Chennai,"Latex, Paginator, Tex"
9,Shirish Anand Koshti,Company Recruiter,3B BlackBio Biotech (I) Ltd.,Bhopal,"Business Development, Life Sciences, Diagnosti..."
10,Charu Saini,Company Recruiter,OESPL PVT LTD,Noida,"Marketing, Civil Construction, Project Managem..."
11,Prerna Mohan,Company Recruiter,Prerna Mohan Design Studio,Delhi,"Interiors, Interior Designing, Interior Decora..."
12,Pralhad DHUMAL,Company Recruiter,FOX SOLUTIONS,MAHARASHTRA,"Plc, Scada, Vfd Drives, Industrial Automation,..."
13,Manav Arora,Company Recruiter,Rapid Cargo Solutions,Delhi,"Telecalling, Data Entry, Office Assistance"
14,Sonali Priya,Company Recruiter,VMC TECHNOLOGIES PRIVATE LIMITED,Bengaluru / Bangalore,"Sales, Crm, Technical Support, Finance, Engine..."
15,Prarit Gupta,Human Resource Manager,HMS Relations Management,Delhi,"Counter Sales, Sales"
16,Raghu Hrexecutive,Human Resource manager,IQs soft,Bengaluru / Bangalore,"Java/J2ee ( Core Java, Struts, Hibernate, Serv..."
17,Take jobs,Human Resources,Take Jobs,Delhi,"tally, Bank Reconciliation, billing, electrica..."
18,iNFIN Technologies,Human Resources,Infin Software Technologies Pvt. Ltd,Chandigarh,"Technical, PHP, Web Development, Web Technolog..."
19,Punit Kumar Bhidodiya,Human Resource Manager,Exatip Technologies,Indore,"Software Development, Business Development"
20,Ishan Ahmed,Human Resource Manager,Jute Wonders Unlimited,Delhi,Back Office
21,Sreekanth Menon,Human Resources,Sterlite Technologies Ltd. Elitecore,Ahmedabad,"C++, Java/j2ee, C, Networking, Radius, Diamete..."
22,Abhishek,Human Resource Manager,Infosys Technology,Hyderabad / Secunderabad,"Sap Abap, Sap Basis, Sap Fico, Sap Bi, java, C..."
23,TechCube IT Services Pvt Ltd,Human Resource Manager,TechCube IT Services Pvt Ltd,Mohali,Skills- Technical Troubleshooting / Sales / Up...

In [32]:
driver.close()

### 8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [33]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2940679144.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [34]:
#scrapping book names
Book=[]
try:
    names=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in names:
        Book.append(i.text)
except NoSuchElementException:              
    Book.append('No details')
time.sleep(2)

#scrapping author names
Author=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        Author.append(i.text)
except NoSuchElementException:
    Author.append('No details')
time.sleep(2)

#scrapping Sales
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:
    Sale.append('No details')
time.sleep(2)    

#scrapping publisher
Publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        Publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    Publisher.append('No details')
time.sleep(2)

#scraping genre
Genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        Genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    Genre.append('No details')
time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2599796389.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2599796389.py:14: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2599796389.py:24: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2599796389.py:34: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2599796389.py:44: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")

In [35]:
print(len(Book),len(Author),len(Sale),len(Publisher),len(Genre))

100 100 100 100 100

In [36]:
#creating dataframe
TopBooks=pd.DataFrame({"Book_name":Book,
                "Author_name":Author,
                'Volume sold':Sale,
                'Publisher':Publisher,
                'Genre':Genre})
TopBooks

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [37]:
driver.close()

### 9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/
You have to find the following details: A) Name
B) Year span
C) Genre
D) Run time E) Ratings F) Votes

In [38]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://www.imdb.com/list/ls095964455/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/1322115350.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [39]:
# scraping name of webseries
Name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        Name.append(i.text)
except NosuchElementException:
    Name.append('No details')
    
time.sleep(2)


# scraping year of release
Year=[]
try:
    release=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in release:
        Year.append(i.text)
except NosuchElementException:
    Year.append('No details')

time.sleep(2)


# scraping genre
Genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('No details')

time.sleep(2)

# scraping run_time
run_time=[]
try:
    rt=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in rt:
        run_time.append(i.text)
except NoSuchElementException:
    run_time.append('No details') 
time.sleep(2)


# scraping rating
Ratings=[]
try:
    rate=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in rate:
        Ratings.append(i.text)
except NoSuchElementException:
    Ratings.append('No details')

time.sleep(2)

# scraping votes
Votes=[]
try:
    vt=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in vt:
        Votes.append(i.text)
except NoSuchElementException:
    Votes.append('No details')

time.sleep(2)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3028935043.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3028935043.py:16: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  release=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3028935043.py:28: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  genres=driver.find_elements_by_xpath("//span[@class='genre']")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3028935043.py:39: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  rt=driver.find_elements_by_xpath("//span[@class='runtime']")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3028935043.py:50: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  rate=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/3028935043.py:61: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  vt=driver.find_elements_by_xpath("//span[@name='nv']")

In [40]:
print(len(Name),len(Year),len(run_time),len(Votes),len(Genre),len(Ratings))

100 100 100 100 100 100

In [41]:
#dataframe
Most_Watched_TV=pd.DataFrame({"Name":Name,
                "Year_span":Year,
                "Genre":Genre,
                "Run_time":run_time,
                "Ratings":Ratings,
                "Votes":Votes})
Most_Watched_TV

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,995,240"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,035,971"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"949,694"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"283,771"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"243,564"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,876"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,554"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"190,477"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,307"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"228,859"

In [42]:
driver.close()

### 10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name B) Data type
C) Task
D) Attribute type E) No of instances F) No of attribute G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [43]:
driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")
#open a website
url='https://archive.ics.uci.edu/'
driver.get(url)
time.sleep(3)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/4136679761.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("/Users/sraazi_reni/Downloads/chromedriver")

In [44]:
#view all datasets link

ds=driver.find_element_by_xpath("//a[@href='datasets.php']")
ds.click()
time.sleep(1)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/2134609939.py:3: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  ds=driver.find_element_by_xpath("//a[@href='datasets.php']")

In [45]:
#scroll
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,10000)")
time.sleep(2)

In [46]:
# creating variables to store the data
Name = []
Data_type = []
Task = []
Attribute = []
Instance = []
No_of_attribute = []
Year = []

#scraping the dataset name
for n in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]'):
    Name.append(i.text)
    
#scraping the data type
for d in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]'):
    Data_type.append(j.text)
    
#scraping the task
for t in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]'):
    Task.append(k.text)
    
#scraping the attribute type
for a in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]'):
    Attribute.append(l.text)
    
#scraping the number of instance
for i in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]'):
    Instance.append(m.text)
    
#scraping the number of attribute
for o in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]'):
    No_of_attribute.append(n.text)
    
#scraping the year
for y in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]'):
    Year.append(o.text)

/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:11: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]'):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:15: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for j in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]'):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:19: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for k in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]'):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:23: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for l in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]'):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:27: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for m in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]'):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:31: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for n in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]'):
/var/folders/kv/5_zby7sj1d1drptxz1qp_z9h0000gn/T/ipykernel_803/826914083.py:35: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for o in driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]'):

In [47]:
print(len(Name),len(Data_type),len(No_of_attribute),len(Attribute),len(Instance),len(Year),len(Task))

623 623 623 623 623 623 623

In [48]:
#creating the dataframe
Datasets = pd.DataFrame({'Dataset Name': Name,'Data Type': Data_type,'Task': Task,'Attribute Type': Attribute,
                        'Number of Instance': Instance,'Number of Attribute': No_of_attribute,'Year': Year})
Datasets

,Dataset Name,Data Type,Task,Attribute Type,Number of Instance,Number of Attribute,Year
0,Name,Data Types,Default Task,Attribute Types,# Instances,# Attributes,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
...,...,...,...,...,...,...,...
618,Influenza outbreak event prediction via Twit...,Multivariate,Classification,"Integer, Real",75840,525,2020
619,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
620,Maternal Health Risk Data Set,,Classification,,1014,7,2020
621,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
622,Image Recognition Task Execution Times in Mo...,Univariate,Regression,Real,4000,2,2021

## Finished